// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5R59W44CUBTFNNhzE_afYxVUBmJrwhek',
    appId: '1:675867067235:web:0de1e1aab96862a8f84956',
    messagingSenderId: '675867067235',
    projectId: 'medipal-9cc60',
    authDomain: 'medipal-9cc60.firebaseapp.com',
    databaseURL: 'https://medipal-9cc60-default-rtdb.firebaseio.com',
    storageBucket: 'medipal-9cc60.appspot.com',
    measurementId: 'G-M0KN12CVFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmIvFFLAsHzklszqfL90QvGf5Zjg522Wg',
    appId: '1:675867067235:android:75216368d5ab88b4f84956',
    messagingSenderId: '675867067235',
    projectId: 'medipal-9cc60',
    databaseURL: 'https://medipal-9cc60-default-rtdb.firebaseio.com',
    storageBucket: 'medipal-9cc60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxcxLbmyj2ttI19pFo6qZsK3zRoo_xNLo',
    appId: '1:675867067235:ios:94534416f0a5136ef84956',
    messagingSenderId: '675867067235',
    projectId: 'medipal-9cc60',
    databaseURL: 'https://medipal-9cc60-default-rtdb.firebaseio.com',
    storageBucket: 'medipal-9cc60.appspot.com',
    iosBundleId: 'com.example.medipal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxcxLbmyj2ttI19pFo6qZsK3zRoo_xNLo',
    appId: '1:675867067235:ios:e30c2a5b9b2940e8f84956',
    messagingSenderId: '675867067235',
    projectId: 'medipal-9cc60',
    databaseURL: 'https://medipal-9cc60-default-rtdb.firebaseio.com',
    storageBucket: 'medipal-9cc60.appspot.com',
    iosBundleId: 'com.example.medipal.RunnerTests',
  );
}
